### ISSUE TITLE
Intermediate container tags

### ISSUE THREAD

**Issue by johanneskiesel** [osirrc2019/jig#10]
The current implementation of "prepare" commits a new image (same image name, tag: "save") at its end:
https://github.com/osirrc2019/jig/blob/4e3765cd59b0869c354b2d7c6f9da826624e470e/run.py#L47

This means there is always at most one prepared image for every original image. Thus, if I want to switch back-and-forth between different versions of the same image or different collections, I need to call prepare, every time I switch.

The alternative would be to append the version and collection name to the tag: `tag="{}-collection-{}".format(args.tag, args.collection_name)` (or similar).

Also: Should something similar then be done after training? This could lead to rather long tags.

**Comment by lintool** [comment]
Should probably be a command line argument passed to the jig? In the find end state, the jig is probably going to be called by something else in turn (e.g., the web app, triggered by some user action). Whatever that thing is can set the tag?

**Comment by charW** [comment]
I don't recommend having the tag for the committed image be `<tag>-<collection1>-<collection2>-...` as the tag can indeed get very long if you train with multiple collections and can easily exceed the max allowed length. The collection list information can be stored/displayed elsewhere in the future if needed. I'd just accept an optional command line argument for the tag, and if that's not provided, default the tag to something like `<tag>-save`.

**Comment by r-clancy** [comment]
Fixed in https://github.com/osirrc2019/jig/pull/32
