### ISSUE TITLE
Separate scripts for each step

### ISSUE THREAD

**Issue by johanneskiesel** [osirrc2019/jig#12]
Having one script per step makes it easier to comprehend the code when the code per step grows larger.

**Comment by lintool** [comment]
I prefer subcommands but am open for discussion.

**Comment by r-clancy** [comment]
We could split the code into different files for readability and still keep the sub-commands, a happy medium?

**Comment by johanneskiesel** [comment]
Sounds good to me!

**Comment by r-clancy** [comment]
Fixed in https://github.com/osirrc2019/jig/pull/20
