### ISSUE TITLE
Start documenting specs

### ISSUE THREAD

**Issue by lintool** [osirrc2019/jig#17]
We should start converting inline code comments into a spec sheet on the workshop homepage: https://github.com/osirrc2019/osirrc2019.github.io

The `init` and `index` hooks seem reasonably vetted?

**Comment by r-clancy** [comment]
`init` and `index` do seem pretty stable... not sure much will change there now.

Would a copy-paste of [this](https://github.com/osirrc2019/jig/tree/dev#docker-container-contract) section do for the website?

**Comment by lintool** [comment]
Yea, that's exactly it. On second thought, maybe just leave it with the jig repo... no need to put on website? If that's the case, then we can close this issue...

**Comment by r-clancy** [comment]
I'd be fine with leaving it in the repo, let's close this then?

**Comment by lintool** [comment]
Closing.
