### ISSUE TITLE
Add ability to drop image into container for interactive session

### ISSUE THREAD

**Issue by lintool** [osirrc2019/jig#34]
This should be a sub-command to be able to drop an image (e.g., after init) into an interactive session. Then we could ssh into it and poke around. In the case of Elasticsearch, we could point a browser at a port and run interactive IR...

**Comment by charW** [comment]
Just to clarify: do you mean that we should be able to pass in command-line arguments for `python run.py prepare` and `python run.py search` so that after it does the preparing/searching, jig does not exit, and we can then interact with the running container in another process?

**Comment by r-clancy** [comment]
So we want a `--keep-alive` flag or something that'll keep the container alive after `prepare` so we can `docker exec -it <name> sh` into after and be able to access services that have had their ports exposed, i.e. elasticsearch

**Comment by lintool** [comment]
I don't think it should be a flag... wouldn't it be easier as a subcommand just to drop the current image into a container? So it's not tied to any specific hooks?

**Comment by charW** [comment]
Then, we can just start a container running in the background with `docker run -it -d <image> /bin/bash` and then interact with it through `docker exec -it <container_id> ...`. We don't need any additional code. Or maybe I'm still not quite understanding your intentions here?
