### ISSUE TITLE
How is search time measured?

### ISSUE THREAD

**Issue by amallia** [osirrc2019/jig#35]
How will efficiency be measured? 
The following `search` script runs multiple tasks, how are you going to measure time?

https://github.com/osirrc2019/anserini-docker/blob/e7ede77ffa73f5f0092e67576ec074b7f27432b7/search#L15-L20

**Comment by lintool** [comment]
It'll have to be by the contract of the hook? @andrewtrotman ?

**Comment by lintool** [comment]
duplicate of #23 

Closing this issue in favor of the other.
