### ISSUE TITLE
Only one run per image?

### ISSUE THREAD

**Issue by andrewtrotman** [osirrc2019/jig#36]
I want to compare multiple runs of my own search engine. An example is passing different BM25 parameters to it.  At the moment there is no assumption of one run per docker image, but also no assumption of otherwise.  If we want to do timings of runs then we need a way to seperate the runs and to get multiple results.  Can we please have a protocol to the jig that lets me pass parameters to my search engine at search time?

**Comment by r-clancy** [comment]
I think the one run assumption is reasonable and will help with the efficiency measures. We can add a `--opts` parameter (for `index` and `search`, I guess) that will be passed through to the container.

**Comment by r-clancy** [comment]
Closing this - we're now able to pass parameters through to `index` and `search` and the documentation has been updated for the assumption of a single search per run.
