### ISSUE TITLE
Collection and topic examples

### ISSUE THREAD

**Issue by hscells** [osirrc2019/jig#40]
Can you please provide some documentation or examples of the file formats for the collections, and file formats for the topics? And will there be any arguments to the jig which specify the input file format of the collection/topics?

Thanks

**Comment by r-clancy** [comment]
The file formats are dependent on the collection, which right now are [core17](https://trec-core.github.io/2017/), [core18](https://trec-core.github.io/2018/), and [robust04](https://trec.nist.gov/data_disks.html). These are in `trecweb`, `trectext`, or `json` format, here are some resources I was able to dig up:
- [core18](https://trec.nist.gov/data/wapost/)
- [trectext / trecweb](https://sourceforge.net/p/lemur/wiki/Quick%20Start/) (see "Example Formats for input data files")
- [Java - trectext](https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/collection/TrecCollection.java)
- [Java - trecweb](https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/collection/TrecwebCollection.java)

topics: https://github.com/castorini/Anserini/tree/master/src/main/resources/topics-and-qrels

In terms of arguments, that's being tracked in https://github.com/osirrc2019/jig/issues/24.
