### ISSUE TITLE
Clarify jig 'search' subcommand

### ISSUE THREAD

**Issue by lintool** [osirrc2019/jig#47]
- Please clarify in documentation (README) `--output` and `--qrels`: relative path appears to work... I remember in a previous absolute paths were required?

- What's the rationale for `--topic` being inconsistent with the two options above?
> the name (not path) of the topic file

Why not have a path here also?

- What's the rationale for having `--save_id`? Presumably, search is stateless (unlike `index` and `init`) right?

**Comment by r-clancy** [comment]
> * Please clarify in documentation (README) `--output` and `--qrels`: relative path appears to work... I remember in a previous absolute paths were required?

The current documentation has the relative/absolute note removed, either of them work now.

> * What's the rationale for `--topic` being inconsistent with the two options above?
> > the name (not path) of the topic file

> Why not have a path here also?

Poor design choice - will create an issue to address.

> * What's the rationale for having `--save_id`? Presumably, search is stateless (unlike `index` and `init`) right?

`--save_id` allows you to have multiple images saved for different collections - if we index with `wapo` with `anserini:latest` and later `nyt` with `anserini:latest` without specifying a different `save_id` (which is used to compute a hash for the snapshot container's tag), `nyt` would overwrite `wapo` (which is the default behavior, if you don't change `save_id` from it's default value).

**Comment by lintool** [comment]
Sorry, clarification:

What's the rationale for having `--save_id` **for `search`**? Presumably, `search` is stateless (unlike `index` and `init`) right?

**Comment by r-clancy** [comment]
> What's the rationale for having `--save_id` **for `search`**? Presumably, `search` is stateless (unlike `index` and `init`) right?

Ahh - for `search` we need to know which image to use. For example, I could index `core17` using the `-storeRawDocs` and `-storeTransformedDocs` flags in Anserini, using a different `save_id` for each which would keep them both saved and available to search over (which saves re-indexing each time). When actually calling `search`, I could specify which one to use.

The flow is like this:
1. `init` + `index` on `anserini:latest` and then save `anserini:hash(latest + save_id)`
2. `search` on  `anserini:hash(latest + save_id)`

**Comment by lintool** [comment]
Ohhhhh... I get it. The `--save_id` in `search` is the image to _load_. Not what to save _after_ you do the search. Because in `prepare`, `--save_id` is what we _save_ to, right?

See my confusion?

**Comment by r-clancy** [comment]
Yeah, I guess the naming of the parameter (or documentation) is a bit confusing. I'll make a slight change of documentation, if it's not clear we can re-name the param.

**Comment by r-clancy** [comment]
Actually it looks like it's been updated in one of the PRs... https://github.com/osirrc2019/jig/pull/46

**Comment by lintool** [comment]
>  if it's not clear we can re-name the param.

Why not? Are jig params breaking changes?

What about being explicit? e.g., `--save-to-tag` and `--load-from-tag`

**Comment by r-clancy** [comment]
> > if it's not clear we can re-name the param.
> 
> Why not? Are jig params breaking changes?
> 
> What about being explicit? e.g., `--save-to-tag` and `--load-from-tag`

Alright, I'll update once the current PRs are merged to avoid conflicts as they touch the same code/docs.
