### ISSUE TITLE
Refactor into subcommands

### ISSUE THREAD

**Issue by lintool** [osirrc2019/jig#5]
The current cmdline arg structure is likely to get too unwieldy soon... I'd suggesting refactoring into subcommands, so we'd have something like:

```
# run init/index hook
run prepare --image ... --tag foo_initialized

# run search hook
run search --topics ...
```

Thoughts?

**Comment by lintool** [comment]
Checking to see if Slack integration works...

**Comment by r-clancy** [comment]
Sounds good - I'll make changes.
