### ISSUE TITLE
Make topic and qrels parameter consistent

### ISSUE THREAD

**Issue by lintool** [osirrc2019/jig#56]
Currently, we have:

```
python run.py search \
    --repo osirrc2019/anserini \
    --tag latest \
    --collection [name] \
    --topic [topic_file_name] \
    --output /path/to/output \
    --qrels $(pwd)/qrels/[qrels]
```

The inconsistency between `--topic` (which assumes a file name under `topics/`) and `--qrels` (which can be any arbitrary path) is annoying. Can we change both to paths, so that:

```
python run.py search \
    --repo osirrc2019/anserini \
    --tag latest \
    --collection [name] \
    --topic /path/to/topics \
    --output /path/to/output \
    --qrels /path/to/qrels
```

**Comment by r-clancy** [comment]
This change was merged into dev and is part of the current PR (https://github.com/osirrc2019/jig/pull/57), going to close this one.
