### ISSUE TITLE
docker tag too long

### ISSUE THREAD

**Issue by matthew-z** [osirrc2019/jig#66]
currently the preparer will generate a new docker tag like 

8a2cf31466141a6d50222cbbee611abb715fa3badcc39a668acf15610579d7bc

I think it is really too long, which makes some output from docker commands ugly (e.g., `docker image ls`).  I think the first 5 characters are enough

**Comment by r-clancy** [comment]
The user of `jig` never needs to interact with the tag, it's used internally for the intermediate images when snapshotting. Going to close this for now as it's more of a cosmetic thing...
