### ISSUE TITLE
Image specific parameters

### ISSUE THREAD

**Issue by amallia** [osirrc2019/jig#67]
I was wondering if it makes sense to have image specific parameters.
For example, PISA can run several query processing algorithm and it would be nice to have the possibility to pass a parameter when invoking the search hook.  Other examples are the scoring function name or a query rewriting enabling flag. 
In this way, we could do several run by using the same script and each of them will produce a different result. 

It could be implemented as a json sub-object named `custom` which will be in the format the image owners prefer.

**Comment by r-clancy** [comment]
There is already support for something like this via the `--opts` parameter, see [here](https://github.com/osirrc2019/jig#command-line-options---prepare) and [here](https://github.com/osirrc2019/jig#index).

**Comment by amallia** [comment]
Thank you
